#!/bin/bash
#SBATCH --job-name=jupyter
#SBATCH --partition=gpu-rtx6k
#SBATCH --account=ml4ml
#SBATCH --nodes=1
#SBATCH --cpus-per-task=18
#SBATCH --gres=gpu:2
#SBATCH --mem=300G
#SBATCH --time=48:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=sidlak@uw.edu

# I use source to initialize conda into the right environment.
source ~/.bashrc
conda activate /gscratch/ml4ml/sidlak/superfold/envs/pyroml

cat $0
echo "--------------------"

jupyter notebook --no-browser --ip 0.0.0.0 --port=8888
--------------------
[W 2022-09-07 14:46:52.517 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-07 14:46:52.518 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-07 14:46:52.518 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-07 14:46:52.518 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-09-07 14:46:52.518 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-09-07 14:46:52.525 LabApp] JupyterLab extension loaded from /gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/jupyterlab
[I 2022-09-07 14:46:52.525 LabApp] JupyterLab application directory is /mmfs1/gscratch/ml4ml/sidlak/superfold/envs/pyroml/share/jupyter/lab
/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/jupyter_server_mathjax/app.py:40: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  help=_("""The MathJax.js configuration file that is to be used."""),
[I 14:46:56.297 NotebookApp] Serving notebooks from local directory: /mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules
[I 14:46:56.297 NotebookApp] Jupyter Notebook 6.4.5 is running at:
[I 14:46:56.297 NotebookApp] http://g3022:8888/
[I 14:46:56.297 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 14:49:09.665 NotebookApp] 302 GET / (10.64.64.8) 0.550000ms
[I 14:49:09.693 NotebookApp] 302 GET /tree? (10.64.64.8) 0.590000ms
[I 14:49:15.861 NotebookApp] 302 POST /login?next=%2Ftree%3F (10.64.64.8) 147.500000ms
[I 14:49:31.339 NotebookApp] Kernel started: e320c7b8-7dc5-4444-97ed-532f4f9786c4, name: python3
[I 14:50:05.923 NotebookApp] Starting buffering for e320c7b8-7dc5-4444-97ed-532f4f9786c4:2c2e9fd9555d4eda8a0f4f592d690d5b
[I 14:50:07.243 NotebookApp] Kernel restarted: e320c7b8-7dc5-4444-97ed-532f4f9786c4
[I 14:50:07.294 NotebookApp] Restoring connection for e320c7b8-7dc5-4444-97ed-532f4f9786c4:2c2e9fd9555d4eda8a0f4f592d690d5b
[W 14:50:11.805 NotebookApp] Nudge: attempt 10 on kernel e320c7b8-7dc5-4444-97ed-532f4f9786c4
[I 14:50:15.285 NotebookApp] Replaying 21 buffered messages
[I 14:51:30.073 NotebookApp] Saving file at /AutoEncoder.ipynb
[I 15:09:30.562 NotebookApp] Saving file at /AutoEncoder.ipynb
[I 15:13:30.029 NotebookApp] Saving file at /AutoEncoder.ipynb
[I 15:15:30.005 NotebookApp] Saving file at /AutoEncoder.ipynb
[I 15:17:51.127 NotebookApp] Saving file at /AutoEncoder.ipynb
[W 15:42:16.739 NotebookApp] /mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/out.tar.gz is not UTF-8 encoded
[W 15:42:16.740 NotebookApp] 400 GET /api/contents/output_env/out.tar.gz?type=file&format=text&_=1662590536600 (10.64.64.8) 1.550000ms referer=http://localhost:1234/edit/output_env/out.tar.gz
[W 16:05:33.854 NotebookApp] delete /output_env
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/output_env'
[W 16:05:37.429 NotebookApp] Unhandled error
[E 16:05:37.430 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:05:37.430 NotebookApp] 500 DELETE /api/contents/output_env (10.64.64.8) 3576.200000ms referer=http://localhost:1234/tree
[W 16:06:01.587 NotebookApp] delete /output_env/bfd.mgnify30.metaeuk30.smag30.a3m
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/bfd.mgnify30.metaeuk30.smag30.a3m (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/bfd.mgnify30.metaeuk30.smag30.a3m', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/bfd.mgnify30.metaeuk30.smag30.a3m' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/bfd.mgnify30.metaeuk30.smag30.a3m'
[W 16:06:01.588 NotebookApp] Unhandled error
[E 16:06:01.589 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:01.589 NotebookApp] 500 DELETE /api/contents/output_env/bfd.mgnify30.metaeuk30.smag30.a3m (10.64.64.8) 2.430000ms referer=http://localhost:1234/tree/output_env
[I 16:06:01.816 NotebookApp] Saving file at /AutoEncoder.ipynb
[W 16:06:03.098 NotebookApp] delete /output_env/out.tar.gz
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/out.tar.gz (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/out.tar.gz', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/out.tar.gz' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/out.tar.gz'
[W 16:06:03.099 NotebookApp] Unhandled error
[E 16:06:03.100 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:03.100 NotebookApp] 500 DELETE /api/contents/output_env/out.tar.gz (10.64.64.8) 2.580000ms referer=http://localhost:1234/tree/output_env
[W 16:06:03.100 NotebookApp] delete /output_env/msa.sh
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/msa.sh (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/msa.sh', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/msa.sh' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/msa.sh'
[W 16:06:03.101 NotebookApp] Unhandled error
[E 16:06:03.101 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:03.101 NotebookApp] 500 DELETE /api/contents/output_env/msa.sh (10.64.64.8) 3.560000ms referer=http://localhost:1234/tree/output_env
[W 16:06:03.102 NotebookApp] delete /output_env/pdb70.m8
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/pdb70.m8 (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/pdb70.m8', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/pdb70.m8' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/pdb70.m8'
[W 16:06:03.103 NotebookApp] Unhandled error
[E 16:06:03.103 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:03.103 NotebookApp] 500 DELETE /api/contents/output_env/pdb70.m8 (10.64.64.8) 1.950000ms referer=http://localhost:1234/tree/output_env
[W 16:06:03.103 NotebookApp] delete /output_env/uniref.a3m
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/uniref.a3m (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/uniref.a3m', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/uniref.a3m' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/uniref.a3m'
[W 16:06:03.104 NotebookApp] Unhandled error
[E 16:06:03.104 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:03.104 NotebookApp] 500 DELETE /api/contents/output_env/uniref.a3m (10.64.64.8) 2.880000ms referer=http://localhost:1234/tree/output_env
[W 16:06:22.614 NotebookApp] delete /output_env/bfd.mgnify30.metaeuk30.smag30.a3m
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/bfd.mgnify30.metaeuk30.smag30.a3m (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/bfd.mgnify30.metaeuk30.smag30.a3m', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/bfd.mgnify30.metaeuk30.smag30.a3m' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/bfd.mgnify30.metaeuk30.smag30 1.a3m'
[W 16:06:22.617 NotebookApp] Unhandled error
[E 16:06:22.617 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:22.617 NotebookApp] 500 DELETE /api/contents/output_env/bfd.mgnify30.metaeuk30.smag30.a3m (10.64.64.8) 3.310000ms referer=http://localhost:1234/tree/output_env
[I 16:06:35.634 NotebookApp] Kernel shutdown: e320c7b8-7dc5-4444-97ed-532f4f9786c4
[W 16:06:38.406 NotebookApp] Session not found: session_id='557df98b-7935-4be5-8526-825011cc87cf'
[W 16:06:38.406 NotebookApp] 404 DELETE /api/sessions/557df98b-7935-4be5-8526-825011cc87cf (10.64.64.8) 0.630000ms referer=http://localhost:1234/notebooks/AutoEncoder.ipynb
[W 16:06:43.751 NotebookApp] delete /output_env/out.tar.gz
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/out.tar.gz (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/out.tar.gz', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/out.tar.gz' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/out.tar 1.gz'
[W 16:06:43.753 NotebookApp] Unhandled error
[E 16:06:43.753 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:43.754 NotebookApp] 500 DELETE /api/contents/output_env/out.tar.gz (10.64.64.8) 3.310000ms referer=http://localhost:1234/tree/output_env
[W 16:06:43.754 NotebookApp] delete /output_env/msa.sh
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/msa.sh (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/msa.sh', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/msa.sh' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/msa 1.sh'
[W 16:06:43.755 NotebookApp] Unhandled error
[E 16:06:43.755 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:43.755 NotebookApp] 500 DELETE /api/contents/output_env/msa.sh (10.64.64.8) 4.500000ms referer=http://localhost:1234/tree/output_env
[W 16:06:43.755 NotebookApp] delete /output_env/bfd.mgnify30.metaeuk30.smag30.a3m
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/bfd.mgnify30.metaeuk30.smag30.a3m (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/bfd.mgnify30.metaeuk30.smag30.a3m', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/bfd.mgnify30.metaeuk30.smag30.a3m' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/bfd.mgnify30.metaeuk30.smag30 2.a3m'
[W 16:06:43.757 NotebookApp] Unhandled error
[E 16:06:43.757 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:43.757 NotebookApp] 500 DELETE /api/contents/output_env/bfd.mgnify30.metaeuk30.smag30.a3m (10.64.64.8) 5.800000ms referer=http://localhost:1234/tree/output_env
[W 16:06:43.769 NotebookApp] delete /output_env/uniref.a3m
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/uniref.a3m (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/uniref.a3m', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/uniref.a3m' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/uniref 1.a3m'
[W 16:06:43.771 NotebookApp] Unhandled error
[E 16:06:43.771 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:43.771 NotebookApp] 500 DELETE /api/contents/output_env/uniref.a3m (10.64.64.8) 1.860000ms referer=http://localhost:1234/tree/output_env
[W 16:06:43.771 NotebookApp] delete /output_env/pdb70.m8
NotebookApp - ERROR - Uncaught exception DELETE /api/contents/output_env/pdb70.m8 (10.64.64.8)
HTTPServerRequest(protocol='http', host='localhost:1234', method='DELETE', uri='/api/contents/output_env/pdb70.m8', version='HTTP/1.1', remote_ip='10.64.64.8')
Traceback (most recent call last):
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 242, in delete
    yield maybe_future(cm.delete(path))
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 279, in delete
    self.delete_file(path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 533, in delete_file
    send2trash(os_path)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 211, in send2trash
    trash_move(path_b, dest_trash, topdir)
  File "/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/send2trash/plat_other.py", line 117, in trash_move
    os.rename(src, op.join(filespath, destname))
OSError: [Errno 18] Invalid cross-device link: b'/mmfs1/gscratch/ml4ml/sidlak/superfold/superfold/Deep-Molecules/output_env/pdb70.m8' -> b'/mmfs1/home/sidlak/.local/share/Trash/files/pdb70 1.m8'
[W 16:06:43.773 NotebookApp] Unhandled error
[E 16:06:43.773 NotebookApp] {
      "Host": "localhost:1234",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349",
      "X-Requested-With": "XMLHttpRequest",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:1234",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:1234/tree/output_env",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_ga=GA1.1.2042086844.1645740279; _ga_6NJ57TMFPZ=GS1.1.1651621253.86.0.1651621253.0; _xsrf=2|a7a4be49|4dbd36c07fc14ce1d236df4a2ea7ecd3|1662587349; username-localhost-1234=\"2|1:0|10:1662587355|23:username-localhost-1234|44:NDYyZmEzY2E0YTg2NDUyZGI1ZDg1YjZkYjk2OTJlYWI=|ec844a2b4415dae3ba37abdc8dfd9688e204d2db0ec4721ffdce43a17744370e\""
    }
[E 16:06:43.773 NotebookApp] 500 DELETE /api/contents/output_env/pdb70.m8 (10.64.64.8) 1.840000ms referer=http://localhost:1234/tree/output_env
[W 16:07:33.351 NotebookApp] No such file or directory: output_env
[W 16:07:33.352 NotebookApp] 404 GET /api/contents/output_env?type=directory&_=1662587356929 (10.64.64.8) 7.170000ms referer=http://localhost:1234/tree/output_env
[I 16:07:45.547 NotebookApp] Creating new directory in /output
[W 16:08:40.453 NotebookApp] Session not found: session_id='557df98b-7935-4be5-8526-825011cc87cf'
[W 16:08:40.453 NotebookApp] 404 DELETE /api/sessions/557df98b-7935-4be5-8526-825011cc87cf (10.64.64.8) 0.770000ms referer=http://localhost:1234/notebooks/AutoEncoder.ipynb
[I 16:08:40.528 NotebookApp] Kernel started: 3f82f17f-29af-4fc4-95a5-1fa545d30295, name: python3
[I 16:11:09.388 NotebookApp] Starting buffering for 3f82f17f-29af-4fc4-95a5-1fa545d30295:2c2e9fd9555d4eda8a0f4f592d690d5b
[I 16:11:09.715 NotebookApp] Kernel restarted: 3f82f17f-29af-4fc4-95a5-1fa545d30295
[I 16:11:09.814 NotebookApp] Restoring connection for 3f82f17f-29af-4fc4-95a5-1fa545d30295:2c2e9fd9555d4eda8a0f4f592d690d5b
[W 16:11:14.326 NotebookApp] Nudge: attempt 10 on kernel 3f82f17f-29af-4fc4-95a5-1fa545d30295
[I 16:11:14.622 NotebookApp] Replaying 3 buffered messages
[I 16:11:34.401 NotebookApp] Saving file at /AutoEncoder.ipynb
Warning: use "from pymol import cmd" instead of "import cmd"
Done parsing fasta!

using  gpu
  0%|          | 0/1 [00:00<?, ?it/s]Input: e0s0r:   0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/5 [00:00<?, ?it/s][A
Running model_1_ptm_seed_0:   0%|          | 0/5 [00:05<?, ?it/s][A
Running model_1_ptm_seed_0:  20%|██        | 1/5 [02:01<08:07, 121.95s/it][A/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/gscratch/ml4ml/sidlak/superfold/envs/pyroml/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

Running model_2_ptm_seed_0:  20%|██        | 1/5 [02:03<08:07, 121.95s/it][A[I 16:16:23.302 NotebookApp] Saving file at /AutoEncoder.ipynb

Running model_2_ptm_seed_0:  40%|████      | 2/5 [02:47<03:51, 77.28s/it] [A
Running model_3_ptm_seed_0:  40%|████      | 2/5 [02:49<03:51, 77.28s/it][A
Running model_3_ptm_seed_0:  60%|██████    | 3/5 [03:33<02:05, 62.85s/it][A
Running model_4_ptm_seed_0:  60%|██████    | 3/5 [03:34<02:05, 62.85s/it][A
Running model_4_ptm_seed_0:  80%|████████  | 4/5 [04:19<00:56, 56.18s/it][A
Running model_5_ptm_seed_0:  80%|████████  | 4/5 [04:20<00:56, 56.18s/it][A
Running model_5_ptm_seed_0: 100%|██████████| 5/5 [05:05<00:00, 52.35s/it][ARunning model_5_ptm_seed_0: 100%|██████████| 5/5 [05:06<00:00, 61.29s/it]
Input: e0s0r: 100%|██████████| 1/1 [05:06<00:00, 306.45s/it]Input: e0s0r: 100%|██████████| 1/1 [05:06<00:00, 306.45s/it]
e0s0r model_1_ptm_seed_0 recycles:3 tol:7.31 mean_plddt:30.52 pTMscore:0.23 elapsed time (s): 181.27670073509216
e0s0r model_2_ptm_seed_0 recycles:3 tol:5.64 mean_plddt:37.14 pTMscore:0.28 elapsed time (s): 45.55337071418762
e0s0r model_3_ptm_seed_0 recycles:3 tol:4.65 mean_plddt:33.11 pTMscore:0.23 elapsed time (s): 45.65524983406067
e0s0r model_4_ptm_seed_0 recycles:3 tol:4.85 mean_plddt:33.41 pTMscore:0.23 elapsed time (s): 45.98282265663147
e0s0r model_5_ptm_seed_0 recycles:3 tol:2.52 mean_plddt:41.00 pTMscore:0.33 elapsed time (s): 45.5221381187439
[I 16:21:33.301 NotebookApp] Saving file at /AutoEncoder.ipynb
[I 22:59:37.812 NotebookApp] Starting buffering for 3f82f17f-29af-4fc4-95a5-1fa545d30295:2c2e9fd9555d4eda8a0f4f592d690d5b
[I 23:24:50.559 NotebookApp] Restoring connection for 3f82f17f-29af-4fc4-95a5-1fa545d30295:2c2e9fd9555d4eda8a0f4f592d690d5b
[W 15:52:50.561 NotebookApp] WebSocket ping timeout after 119777 ms.
[I 15:52:55.564 NotebookApp] Starting buffering for 3f82f17f-29af-4fc4-95a5-1fa545d30295:2c2e9fd9555d4eda8a0f4f592d690d5b
[I 15:52:58.195 NotebookApp] Restoring connection for 3f82f17f-29af-4fc4-95a5-1fa545d30295:2c2e9fd9555d4eda8a0f4f592d690d5b
[W 15:57:58.197 NotebookApp] WebSocket ping timeout after 112933 ms.
[I 15:58:03.201 NotebookApp] Starting buffering for 3f82f17f-29af-4fc4-95a5-1fa545d30295:2c2e9fd9555d4eda8a0f4f592d690d5b
slurmstepd: error: *** JOB 6128139 ON g3022 CANCELLED AT 2022-09-09T14:46:40 DUE TO TIME LIMIT ***
